private_key = "~/.ssh/id_rsa"
private_key_name = "Your DigitalOcean SSH Key Name"
api_token = "Your DigitalOcean API Token"
droplet_name = "lemp-1"
droplet_size = "s-1vcpu-1gb"
db_password = "password"
server_domain = "example.com"
server_root = "/home/example/public_html"