#! /bin/bash

echo 'Initializing setup..'
for arg in "$@"; do
    if [[ "$arg" =~ ^-- ]]; then
        variable=$(echo $arg | sed 's/^--//')
    else
        declare $variable="$arg"
    fi
done
unalias cp
unalias mv
cd $(dirname "$0")
echo 'fastestmirror=1' >>/etc/dnf/dnf.conf
echo 'max_parallel_downloads=8' >>/etc/dnf/dnf.conf

echo 'Installing required software..'
yum install -y dnf-plugins-core git vim wget glibc-locale-source glibc-langpack-ar
groupadd --gid 101 nginx
useradd -M --uid 101 --gid 101 nginx
yum install -y nginx nginx-mod-http-perl
yum install -y https://rpms.remirepo.net/enterprise/remi-release-9.rpm
dnf config-manager --set-enabled remi
mv resources/config/mariadb.repo /etc/yum.repos.d/
yum install -y php80 php80-php-bcmath php80-php-cli php80-php-common php80-php-fpm php80-php-gd php80-php-intl php80-php-json php80-php-mbstring php80-php-mysqlnd php80-php-pdo php80-php-pecl-geoip php80-php-pecl-imagick php80-php-pecl-zip php80-php-xml php80-runtime php80-php-process php80-php-opcache mariadb-server nodejs
ln -s -T /usr/bin/php80 /usr/bin/php
ln -s -T /opt/remi/php80/root/usr/sbin/php-fpm /usr/bin/php-fpm
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php composer-setup.php
php -r "unlink('composer-setup.php');"
mv composer.phar /usr/bin/composer
chmod +x /usr/bin/composer

echo 'Configuring required software..'
if [ -n "$server_domain" ]; then
    sed -i "s/__domain__/$server_domain/g" resources/config/app.conf
fi
if [ -n "$server_root" ]; then
    sed -i "s/__root_dir__/$server_root/g" resources/config/app.conf
fi
if [ -n "$db_password" ]; then
    sed -i "s/__db_password__/$db_password/g" resources/mariadb_init.sql
fi
mv resources/config/nginx.conf /etc/nginx/
mv resources/config/app.conf /etc/nginx/conf.d/
mv resources/config/php-fpm.conf /etc/opt/remi/php80/
mv resources/config/www.conf /etc/opt/remi/php80/php-fpm.d/
systemctl enable nginx php80-php-fpm mariadb
systemctl start nginx php80-php-fpm mariadb
chown nginx:nginx /var/opt/remi/php80/run/php-fpm/www.sock
mysql < resources/mariadb_init.sql