#! /bin/bash

echo 'Initializing setup..'
for arg in "$@"; do
    if [[ "$arg" =~ ^-- ]]; then
        variable=$(echo $arg | sed 's/^--//')
    else
        declare $variable="$arg"
    fi
done
unalias cp
unalias mv
cd $(dirname "$0")
echo 'fastestmirror=1' >>/etc/dnf/dnf.conf
echo 'max_parallel_downloads=8' >>/etc/dnf/dnf.conf

echo 'Installing required software..'
yum install -y dnf-plugins-core git vim wget glibc-locale-source glibc-langpack-ar
groupadd --gid 9000 nginx
useradd -M --uid 9000 --gid 9000 nginx
yum install -y nginx nginx-mod-http-perl
yum install -y https://rpms.remirepo.net/enterprise/remi-release-9.rpm
dnf config-manager --set-enabled remi
mv resources/config/mariadb.repo /etc/yum.repos.d/
yum install -y php81 php81-php-bcmath php81-php-cli php81-php-common php81-php-fpm php81-php-gd php81-php-intl php81-php-json php81-php-mbstring php81-php-mysqlnd php81-php-pdo php81-php-pecl-geoip php81-php-pecl-imagick php81-php-pecl-zip php81-php-xml php81-runtime php81-php-process php81-php-opcache mariadb-server nodejs
ln -s -T /usr/bin/php81 /usr/bin/php
ln -s -T /opt/remi/php81/root/usr/sbin/php-fpm /usr/bin/php-fpm
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php composer-setup.php
php -r "unlink('composer-setup.php');"
mv composer.phar /usr/bin/composer
chmod +x /usr/bin/composer

echo 'Configuring required software..'
if [ -n "$server_domain" ]; then
    sed -i "s/__domain__/$server_domain/g" resources/config/app.conf
fi
if [ -n "$server_root" ]; then
    sed -i "s/__root_dir__/$server_root/g" resources/config/app.conf
fi
if [ -n "$db_password" ]; then
    sed -i "s/__db_password__/$db_password/g" resources/mariadb_init.sql
fi
mv resources/config/nginx.conf /etc/nginx/
mv resources/config/app.conf /etc/nginx/conf.d/
mv resources/config/php-fpm.conf /etc/opt/remi/php81/
mv resources/config/www.conf /etc/opt/remi/php81/php-fpm.d/
systemctl enable nginx php81-php-fpm mariadb
systemctl start nginx php81-php-fpm mariadb
chown nginx:nginx /var/opt/remi/php81/run/php-fpm/www.sock
mysql < resources/mariadb_init.sql